openapi: 3.0.0
info:
  title: DailyVir
  description: Video sharing website
  contact:
    name: AlexeRazvan
  version: 1.0.0
servers:
- url: /MVC_todo
paths:
  /users/login:
    description: User page
    post:
      description: Login operation
      operationId: usersLoginPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users_login_body'
      responses:
        200:
          description: success and returns some html text
          content:
            text/html:
              schema:
                type: string
              examples:
                html:
                  summary: A list containing two items
                  value: '<html><body><ul><li>item 1</li><li>item 2</li></ul></body></html>'
      x-swagger-router-controller: Default
  /users/signup:
    description: User page
    post:
      description: Signup operation
      operationId: usersSignupPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users_signup_body'
      responses:
        200:
          description: success and returns some html text
          content:
            text/html:
              schema:
                type: string
              examples:
                html:
                  summary: A list containing two items
                  value: '<html><body><ul><li>item 1</li><li>item 2</li></ul></body></html>'
      x-swagger-router-controller: Default
  /videos/create:
    description: User page
    post:
      description: Video upload
      operationId: videosCreatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/videos_create_body'
      responses:
        200:
          description: success and returns some html text
          content:
            text/html:
              schema:
                type: string
              examples:
                html:
                  summary: A list containing two items
                  value: '<html><body><ul><li>item 1</li><li>item 2</li></ul></body></html>'
      x-swagger-router-controller: Default
components:
  schemas:
    users_login_body:
      type: object
      properties:
        login:
          type: integer
          example: 1
        usernamePHP:
          type: string
          example: razvan
        passwordPHP:
          type: string
          example: password
    users_signup_body:
      type: object
      properties:
        signup:
          type: integer
          example: 1
        usernamePHP:
          type: string
          example: razvan
        passwordPHP:
          type: string
          example: password
        emailPHP:
          type: string
          example: password
        countryPHP:
          type: string
          example: password
        genderPHP:
          type: string
          example: password
    videos_create_body:
      type: object
      properties:
        create:
          type: integer
          example: 1
        urlPHP:
          type: string
          example: razvan
        titleUrlPHP:
          type: string
          example: password
        descriptionUrlPHP:
          type: string
          example: password
        categoryUrlPHP:
          type: string
          example: password